# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2023-2026 Intel Corporation
ccflags-y += -DDEFAULT_SYMBOL_NAMESPACE='"INTEL_SSEI"'

obj-$(CONFIG_INTEL_SSEI) += issei.o
issei-objs += cdev.o
issei-objs += dma.o
