/* SPDX-License-Identifier: MIT */
/*
 * Copyright © 2025 Intel Corporation
 */

#ifndef _XE_SC_REGS_H_
#define _XE_SC_REGS_H_

#include "xe_regs.h"

#define SYSCTRL_BASE_OFFSET		0xDB000
#define SYSCTRL_BASE			(SOC_BASE + SYSCTRL_BASE_OFFSET)
#define SYSCTRL_MAILBOX_INDEX		0x03
#define SC_BAR_LENGTH			0x1000

#define SC_MB_CTRL			XE_REG(SYSCTRL_BASE + 0x10)
#define   SC_MB_CTRL_RUN_BUSY		REG_BIT(31)
#define   SC_MB_CTRL_IRQ		REG_BIT(30)
#define   SC_MB_CTRL_RUN_BUSY_OUT	REG_BIT(29)
#define   SC_MB_CTRL_PARAM3		REG_GENMASK(28, 24)
#define   SC_MB_CTRL_PARAM2		REG_GENMASK(23, 16)
#define   SC_MB_CTRL_PARAM1		REG_GENMASK(15, 8)
#define   SC_MB_CTRL_COMMAND		REG_GENMASK(7, 0)

#define SC_MB_DATA0			XE_REG(SYSCTRL_BASE + 0x14)
#define SC_MB_DATA1			XE_REG(SYSCTRL_BASE + 0x18)
#define SC_MB_DATA2			XE_REG(SYSCTRL_BASE + 0x1C)
#define SC_MB_DATA3			XE_REG(SYSCTRL_BASE + 0x20)

#define MKHI_FRAME_PHASE		REG_BIT(24)
#define MKHI_FRAME_CURRENT		REG_GENMASK(21, 16)
#define MKHI_FRAME_TOTAL		REG_GENMASK(13, 8)
#define MKHI_FRAME_COMMAND		REG_GENMASK(7, 0)

#define MKHI_HDR_RESULT			REG_GENMASK(31, 24)
#define MKHI_HDR_IS_RESPONSE		REG_BIT(15)
#define MKHI_HDR_COMMAND		REG_GENMASK(14, 8)
#define MKHI_HDR_GROUP_ID		REG_GENMASK(7, 0)

#define SC_MB_FRAME_SIZE		16
#define SC_MB_MAX_FRAMES		64
#define SC_MB_MAX_MESSAGE_SIZE		(SC_MB_FRAME_SIZE * SC_MB_MAX_FRAMES)
#define SC_MKHI_COMMAND			5

#define SC_MB_DEFAULT_TIMEOUT_MS	500
#define SC_MB_RETRY_TIMEOUT_MS		20
#define SC_MB_POLL_INTERVAL_US		100

#endif /* _XE_SC_REGS_H_ */
