#
# Makefile for intel tsens Thermal Linux driver
#

obj-$(CONFIG_INTEL_TSENS_LOCAL_HOST)	+= intel_tsens_thermal.o
obj-$(CONFIG_INTEL_TSENS_IA_HOST)	+= intel_tsens_host.o
obj-$(CONFIG_KEEMBAY_THERMAL)		+= keembay_thermal.o
