obj-$(CONFIG_XBAY_RAS) += xbay_ras.o
xbay_ras-objs += ras_core.o
xbay_ras-objs += cortex_a53_edac.o
xbay_ras-objs += csram_edac.o
xbay_ras-objs += snps_lpddr_edac.o
xbay_ras-objs += snps_pcie_rasdes.o
